version: '3'

services:  
  frontend:
    build: .
    restart: always
    container_name: frontend
    networks:
      - frontend-network
      - nginx_proxy
networks:
  frontend-network:
    driver: bridge
  nginx_proxy:
    external: true


