image: registry.gitlab.its-dev.ru/coalition/frontend

stages:
  - deploy_staging
  - deploy_prod
before_script:
#  - apk add --no-cache openssh-client rsync
#  - apk add --update --no-cache sshpass
#  - apk add ansible
#  - mkdir -p ~/.ssh
#  - chmod 700 ~/.ssh
  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
  - mkdir server_colation
  - cd server_colation
  - echo -e "$ANSIBLE_HOST" > hosts.txt
  - echo -e "[defaults]\n\nhost_key_checking = false\ninventory = ./hosts.txt" >ansible.cfg

deploy_stag:
  stage: deploy_staging
  script:
     - ls
  only:
    - staging

deploy_prod:
  stage: deploy_prod
  script:
    - ansible -i hosts.txt  produ -m shell -a "bash /var/app/frontend_deploy.sh $GIT_PRIVATE"
  when: manual
  only:
    - master
